# Generated by Django 5.2.6 on 2025-09-16 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0002_category_contactsubmission_dessertitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='order_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('custom-cake', 'Custom Cake Order'), ('catering', 'Catering Request'), ('corporate', 'Corporate Event'), ('wedding', 'Wedding Desserts'), ('complaint', 'Issue/Complaint')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='preferred_contact',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
