# Generated by Django 5.2.6 on 2025-09-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0005_payment_alter_order_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
