# Generated by Django 5.2.6 on 2025-09-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0006_remove_order_payment_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Home Delivery'), ('takeaway', 'Store Pickup')], default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Paid Online'), ('store', 'Pay at Store')], default='online', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('ready', 'Ready for Pickup'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
