# Generated by Django 5.2.6 on 2025-09-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0008_alter_order_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefrecommendation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='chefrecommendation',
            old_name='reason',
            new_name='recommendation_text',
        ),
        migrations.AddField(
            model_name='chefrecommendation',
            name='chef_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chefrecommendation',
            name='chef_name',
            field=models.CharField(default='Chef Maria', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chefrecommendation',
            name='chef_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chefrecommendation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chefrecommendation',
            name='dessert_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sweetapp.dessertitem'),
        ),
    ]
