# Generated by Django 5.2.6 on 2025-09-25 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0009_alter_chefrecommendation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Sweet Dessert', max_length=200)),
                ('hero_subtitle', models.TextField(default='We create exquisite desserts with passion, artistry, and the finest ingredients')),
                ('hero_badge_text', models.CharField(default='🏪 Our Sweet Story', max_length=100)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_text', models.TextField(default="To transform life's precious moments into unforgettable experiences through exceptional desserts.")),
                ('values_title', models.CharField(default='Our Values', max_length=200)),
                ('values_subtitle', models.TextField(default='The principles that guide everything we do, from ingredient selection to customer service.')),
                ('store_title', models.CharField(default='Visit Our Store', max_length=200)),
                ('store_description', models.TextField(default='Step into our warm, inviting space where the aroma of freshly baked goods fills the air.')),
                ('store_address', models.CharField(default='123 Sweet Street, Dessert City, DC 12345', max_length=300)),
                ('store_hours', models.CharField(default='Mon-Thu: 7AM-9PM | Fri-Sun: 7AM-10PM', max_length=200)),
                ('cta_title', models.CharField(default='Ready to Experience Sweet Perfection?', max_length=200)),
                ('cta_subtitle', models.TextField(default="Join thousands of satisfied customers who have made us their go-to destination for life's sweetest moments.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'About Us Page',
                'verbose_name_plural': 'About Us Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_emoji', models.CharField(default='👨\u200d🍳', help_text='Emoji to display as image', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='sweetapp.aboutuspage')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('Heart', 'Heart'), ('Award', 'Award'), ('Users', 'Users'), ('ChefHat', 'Chef Hat'), ('Star', 'Star'), ('Coffee', 'Coffee'), ('Cake', 'Cake'), ('Utensils', 'Utensils')], default='Heart', max_length=50)),
                ('color_gradient', models.CharField(choices=[('from-red-500/20 to-pink-500/20', 'Red to Pink'), ('from-amber-500/20 to-yellow-500/20', 'Amber to Yellow'), ('from-blue-500/20 to-indigo-500/20', 'Blue to Indigo'), ('from-emerald-500/20 to-teal-500/20', 'Emerald to Teal'), ('from-purple-500/20 to-violet-500/20', 'Purple to Violet'), ('from-orange-500/20 to-red-500/20', 'Orange to Red')], default='from-red-500/20 to-pink-500/20', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='sweetapp.aboutuspage')),
            ],
            options={
                'verbose_name': 'About Us Value',
                'verbose_name_plural': 'About Us Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='OurStoryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Our Sweet Journey', max_length=200)),
                ('hero_subtitle', models.TextField(default='From a passionate dream to your favorite dessert destination')),
                ('hero_badge_text', models.CharField(default='✨ Our Story', max_length=100)),
                ('founder_name', models.CharField(default='Noor Ahmed', max_length=100)),
                ('founder_title', models.CharField(default='Founder & Head Pastry Chef', max_length=100)),
                ('founder_image', models.CharField(blank=True, help_text='Path to founder image', max_length=500)),
                ('founder_quote', models.TextField(default='Every dessert tells a story, and every story deserves the perfect sweet ending.')),
                ('founder_description', models.TextField(default='With over a decade of experience in fine pastry arts, I founded Sweet Dessert to bring joy and sweetness to every celebration.')),
                ('journey_title', models.CharField(default='The Journey', max_length=200)),
                ('journey_subtitle', models.TextField(default='From humble beginnings to sweet success')),
                ('impact_title', models.CharField(default='Our Sweet Impact', max_length=200)),
                ('impact_subtitle', models.TextField(default="Celebrating the milestones we've achieved together")),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_text', models.TextField(default="To become the world's most beloved dessert destination, spreading joy one sweet creation at a time.")),
                ('cta_title', models.CharField(default='Be Part of Our Story', max_length=200)),
                ('cta_subtitle', models.TextField(default='Every order, every smile, every celebration becomes part of our sweet journey.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Our Story Page',
                'verbose_name_plural': 'Our Story Pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='e.g., 50,000+', max_length=20)),
                ('label', models.CharField(help_text='e.g., Happy Customers', max_length=100)),
                ('icon', models.CharField(choices=[('Users', 'Users'), ('Heart', 'Heart'), ('Award', 'Award'), ('Star', 'Star'), ('Cake', 'Cake'), ('Coffee', 'Coffee'), ('ChefHat', 'Chef Hat'), ('MapPin', 'Map Pin')], default='Users', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('story_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_metrics', to='sweetapp.ourstorypage')),
            ],
            options={
                'verbose_name': 'Impact Metric',
                'verbose_name_plural': 'Impact Metrics',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='StoryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('Heart', 'Heart'), ('Award', 'Award'), ('Users', 'Users'), ('ChefHat', 'Chef Hat'), ('Star', 'Star'), ('Coffee', 'Coffee'), ('Cake', 'Cake'), ('Sparkles', 'Sparkles'), ('MapPin', 'Map Pin')], default='Heart', max_length=50)),
                ('color_gradient', models.CharField(default='from-pink-500/20 to-red-500/20', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('story_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='sweetapp.ourstorypage')),
            ],
            options={
                'verbose_name': 'Timeline Event',
                'verbose_name_plural': 'Timeline Events',
                'ordering': ['order', 'year'],
            },
        ),
    ]
