# Generated by Django 5.2.6 on 2025-09-25 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0010_aboutuspage_aboutusteammember_aboutusvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('Package', 'Package'), ('CreditCard', 'Credit Card'), ('Truck', 'Truck'), ('Heart', 'Heart'), ('ChefHat', 'Chef Hat'), ('Clock', 'Clock'), ('MapPin', 'Map Pin'), ('Phone', 'Phone'), ('Mail', 'Mail'), ('Star', 'Star'), ('Users', 'Users'), ('Award', 'Award'), ('Coffee', 'Coffee'), ('Cake', 'Cake'), ('Sparkles', 'Sparkles')], default='Package', max_length=50)),
                ('color', models.CharField(choices=[('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('blue', 'Blue'), ('green', 'Green'), ('red', 'Red'), ('yellow', 'Yellow'), ('indigo', 'Indigo')], default='orange', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Frequently Asked Questions', max_length=200)),
                ('subtitle', models.TextField(default='Find answers to commonly asked questions about our desserts, ordering, and services.')),
                ('hero_background_color', models.CharField(default='from-orange-50 to-pink-50', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ Page',
                'verbose_name_plural': 'FAQ Pages',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='sweetapp.faqcategory')),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='faq_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='sweetapp.faqpage'),
        ),
    ]
